spring:
  datasource:
    url: jdbc:h2:mem:blog_db
    username: "sa"
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret: your-very-long-secret-key-at-least-256-bits-long-for-HS256-algorithm
  expiration: 86400000
#logging:
#  level:
#    org.springframework.security: DEBUG